10 rcupration automatique des matchs et des resultats
ask1a/lolprono pull request #22
Opened 2024-04-24 19:11 UTC by GeoffreyRoigDeslandes

C'est pas le plus clean mais pour la première version ça devrait fonctionner. 

Je ferai des amélioration ce weekend probablement. 

Du genre: 
- faire un seul fichier job avec des arguements pour selectionner insert ou update. 
- refactor le code en le mettant en classes (ca devrait sauver pas mal de lignes.

2024-04-24 22:40 UTC, ask1a requested changes
ça prend forme! :)
J'ai commencé à relire et l'absence de tests unitaires ou à minima d'un script qui appelle et utilise les fonctions d'utils rend la révision plus longue. ^^'''
Il manque un ajout dans requirements.txt de bs4.
Je finis de relire demain.

2024-04-24 22:40 UTC, ask1a commented on jobs/utils.py
> +    return -1
```suggestion
return df.loc[df['leaguename']==league_name,'id'].to_dict().get(1)
```
Return None si le league_name n'est pas trouvé

2024-04-24 22:40 UTC, ask1a commented on jobs/utils.py
> +def assign_league_id(league_name, leagues_df):
```suggestion
def assign_league_id(league_name: str, leagues_df: pd.DataFrame) -> None | int | str:
```
typage pour éviter la docstring

2024-04-25 17:20 UTC, GeoffreyRoigDeslandes commented on jobs/utils.py
> +    return -1
Personellement je préfère retourner "-1". Car je sais que  "-1" c'est une valeur intentionelle, alors que pour None ce n'est pas toujours le cas.

2024-04-27 08:35 UTC, GeoffreyRoigDeslandes commented on jobs/utils.py
> +            return 'keep'
Je crois que ça ne fonctionne pas, ou alors je l'applique masl :s 

![image](https://github.com/ask1a/lolprono/assets/157515848/91a4431d-88a8-4bd8-9d93-c5d9310a55bf)

2024-04-27 08:41 UTC, GeoffreyRoigDeslandes commented on jobs/utils.py
> +    game_list = pd.DataFrame(
Parce que dans ma tête la dataframe liste tous les matches à venir. Mais c'est vrai que je n'ai pas pensé à la confusion avec le type.

2024-04-27 08:41 UTC, GeoffreyRoigDeslandes commented on jobs/utils.py
> +    game_list = pd.DataFrame(
Même réponse que tanto 📦

2024-04-27 09:40 UTC, ask1a commented on jobs/utils.py
> +            return 'keep'
Ce print n'est pas un test unitaire, difficile d'arbitrer sur cette base. Quand je teste de mon coté j'obtiens la même chose.

2024-04-27 09:51 UTC, ask1a commented on jobs/utils.py
> +            return 'keep'
ok je pige tu testes qu'un des éléments de la liste contienne la sous-string du leaguename

2024-04-27 09:54 UTC, ask1a commented on jobs/utils.py
> +            return leagues_df[leagues_df['leaguename'] == league]['id'].values[0]
la boucle est bien nécessaire car on test l'existence d'une substring dans une liste de string, mon mauvais.

2024-04-28 18:19 UTC, ask1a approved these changes

2024-04-28 18:19 UTC, merged