Mise en forme du rendu des matchs sur page pronos
ask1a/lolprono pull request #3
Opened 2024-04-10 11:07 UTC by ziedbelhocine

2024-04-10 11:08 UTC, ziedbelhocine commented
C'est bon j'ai fini !

2024-04-21 12:32 UTC, ask1a requested changes
Quelque propositions de modifiactions pour gerer une erreur et un affichage plus logique de la page prono suivant si le pronostic est encore modifiable.

2024-04-21 12:32 UTC, ask1a commented on project/auth.py
> +        columns_to_integer = ['score_team_1', 'score_team_2', 'prono_team_1', 'prono_team_2']
Ajouter l'information "est-ce que le pronostic est encore modifiable ?" , pour différencier l'affichage.
```suggestion
        pronos['editable'] = datetime.now() < pronos["game_datetime"]
        columns_to_integer = ['score_team_1', 'score_team_2', 'prono_team_1', 'prono_team_2']
```

2024-04-21 12:32 UTC, ask1a commented on project/templates/pronos.html
> +                    </div>
si il n'est plus modifiable, alors on affiche le score "en dur" plutôt que dans un formulaire.
```suggestion
                    </div>
                    {% else %}
                    <div class="column">{{item.prono_team_1}}</div>
                    <div class="column">{{item.prono_team_2}}</div>
                    {% endif %}
```

2024-04-21 12:32 UTC, ask1a commented on project/templates/pronos.html
> +                    <div class="column has-text-large">Mon pronostic : </div>
On teste si le pronostic est modifiable, si oui on ne change rien.
```suggestion
                    <div class="column has-text-large">Mon pronostic : </div>
                    {% if item.editable %}
```

2024-04-21 12:38 UTC, ask1a requested changes

2024-04-21 12:38 UTC, ask1a commented on project/templates/pronos.html
> +                    </div>
si il n'est plus modifiable, alors on affiche le score "en dur" plutôt que dans un formulaire. 

```suggestion
                    </div>
                    {% else %}
                    <div class="column">{{item.prono_team_1}}</div>
                    <div class="column">{{item.prono_team_2}}</div>
                    {% endif %}
```

2024-04-21 16:10 UTC, ziedbelhocine commented on project/auth.py
> +        columns_to_integer = ['score_team_1', 'score_team_2', 'prono_team_1', 'prono_team_2']
Ici ça te renvoie un True or False sans methode straptime ?

2024-04-21 16:13 UTC, ziedbelhocine commented
Je ne sais pas si je m'y suis bien pris pour résoudre tous les changements que tu as suggéré mais pour moi c'est ok.

2024-04-23 23:08 UTC, closed without merging